task_management/urls.py
from django.contrib import admin
from debug_toolbar.toolbar import debug_toolbar_urls
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.views import home,no_permission  
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tasks/", include("tasks.urls")),
    path("users/", include("users.urls")),
    path("",home, name="home"),
    path("no-permission",no_permission, name="no-permission"),
] + debug_toolbar_urls()

# ⭐ মিডিয়া ফাইল সার্ভ করার জন্য
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from tasks.views import ( 
    Dashboard,
    Br,  
    Address,
     # -----------------------------
     # Bn HQ
     # -----------------------------
    Force_bio,
    Force_detail,

   
)
# app_name = "tasks"  
urlpatterns = [
    # -----------------------------
    # Manager & User Dashboards
    # -----------------------------
    path('manager-dashboard/', Dashboard, name='manager-dashboard'),
    path('br/', Br, name='br'),
    path('address/<int:member_id>', Address, name='address'),
    # path('user-dashboard/', user_dashboard, name='user-dashboard'),

    # -----------------------------
    # Force Bio  and Bn-HQ
    # -----------------------------
    path('bio/', Force_bio, name='force-bio'),

    path('force/',Force_detail, name='force-detail'),

    # path('br/',  List_of_All_Branch, name='allbr'),
 
    # -----------------------------
    # Company Views
    # -----------------------------
    

    # Optional old path


    # -----------------------------
    # Member Posting View
    # -----------------------------
    # path('member-posting/', member_posting_view, name='member-posting'), 

    # ..................................
    # ALL Company history..............
   


]




















# python manage.py shell 
# from django.template.loader import get_template
# get_template('bnhq/list.html')

tasks/models.py
from django.db import models

# -------------------------------
# 🔹 All Force 
# -------------------------------
class ForceMember(models.Model):
    COM_CHOICES = [
        ('OTHER', '......'),
        ('cpc-1', 'CPC-1'),
        ('cpc-2', 'CPC-2'),
        ('cpc-3', 'CPC-3'),
        ('cpsc', 'CPSC'),
        ('hq', 'HQ'),
        ('Bn HQ', 'Bn HQ'),
        ('ro', 'RO'), 
        ('mi', 'Mi'), 
        ('ab', 'A Branch'), 
    ]

    RANK_CHOICES = [
        ('OTHER', '......'),
        ('OFFICER', 'Offr'),
        ('DAD', 'DAD'),
        ('SI', 'SI'),
        ('ASI', 'ASI'),
        ('NAYEK', 'Nek'),
        ('CONSTABLE', 'Con'),
        ('CIVIL', 'Civ'),
    ]
    FORCE_CHOICES = [
        ('OTHER', '......'),
        ('ARMY', 'Army'),
        ('NAVY', 'Navy'),
        ('AIR', 'Air'),
        ('POLICE', 'Police'),
        ('BGB', 'BGB'),
        ('VDP', 'Ansar VDP'),
        ('CIV', 'Civ'),
    ]

    no = models.IntegerField(unique=True)
    name = models.CharField(max_length=50)
    rank = models.CharField(max_length=20, choices=RANK_CHOICES)
    force = models.CharField(max_length=20, choices=FORCE_CHOICES)

    company = models.CharField(max_length=50, choices=COM_CHOICES, blank=True, null=True)

    svc_join = models.DateField()
    mother_unit = models.CharField(max_length=50)
    rab_join = models.DateField()
    birth_day = models.DateField()  

    nid = models.CharField(max_length=20, unique=True)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15)
    wf_phone = models.CharField(max_length=15)

    def __str__(self):
        return f"{self.get_rank_display()} - {self.name}"

# -------------------------------
# 🔹 Present Address
# -------------------------------
class PresentAddress(models.Model):
    member = models.OneToOneField(
        ForceMember,
        on_delete=models.CASCADE,
        related_name='present_address'
    )
    house = models.CharField(max_length=20)
    road = models.CharField(max_length=20)
    sector = models.CharField(max_length=20)
    village = models.CharField(max_length=20)
    post = models.CharField(max_length=20, default="N/A")
    thana = models.CharField(max_length=30)
    district = models.CharField(max_length=30)
    division = models.CharField(max_length=30)

    def __str__(self):
        return f"Present Address of {self.member.name}"

# -------------------------------
# 🔹 Permanent Address
# -------------------------------
class PermanentAddress(models.Model):
    member = models.OneToOneField(
        ForceMember,
        on_delete=models.CASCADE,
        related_name='permanent_address'
    )
    house = models.CharField(max_length=20)
    road = models.CharField(max_length=20)
    sector = models.CharField(max_length=20)
    village = models.CharField(max_length=20)
    post = models.CharField(max_length=20, default="N/A")
    thana = models.CharField(max_length=30)
    district = models.CharField(max_length=30)
    division = models.CharField(max_length=30)

    def __str__(self):
        return f"Permanent Address of {self.member.name}"

# -------------------------------
# 🔹 Other Related Models (Duty, MI, Ro, AcctBr, TrgBr, Mt)
# -------------------------------
class AcctBr(models.Model):
    member = models.ForeignKey(ForceMember, on_delete=models.CASCADE, related_name='acctbr')
    destination = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.member.name} → {self.destination}"

class Ro(models.Model):
    member = models.ForeignKey(ForceMember, on_delete=models.CASCADE, related_name='ro')
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class MiRoomVisit(models.Model):
    member = models.ForeignKey(ForceMember, on_delete=models.CASCADE, related_name='mi_visits')
    symptoms = models.TextField()
    date = models.DateField(auto_now_add=True)
    treatment = models.TextField()

    def __str__(self):
        return f"{self.member.name} - {self.date}"

class Duty(models.Model):
    member = models.ForeignKey(ForceMember, on_delete=models.CASCADE, related_name='duties')
    name = models.CharField(max_length=50)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        return f"{self.name} ({self.date})"

class Mt(models.Model):
    member = models.ForeignKey(ForceMember, on_delete=models.CASCADE, related_name='mt')
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class TrgBr(models.Model):
    member = models.ForeignKey(ForceMember, on_delete=models.CASCADE, related_name='trg')
    rab_id = models.IntegerField(unique=True)

    def __str__(self):
        return f"TRG for {self.member.name} ({self.rab_id})"



class MemberPosting(models.Model):
    member = models.ForeignKey("ForceMember", on_delete=models.CASCADE)
    status = models.CharField(max_length=20, default="pending")

    def __str__(self):
        return f"{self.member.name} - {self.status}"

tasks/forms.py
from django import forms
from datetime import date, datetime
from .models import ForceMember, PresentAddress, PermanentAddress

current_year = date.today().year

# -------------------------------
# CSS Classes
# -------------------------------
INPUT_CLASSES = "form-input border-blue-500 focus:ring-2 focus:ring-blue-300 rounded-md py-1 px-2"
SELECT_CLASSES = "form-select border-blue-500 focus:ring-2 focus:ring-blue-300 rounded-md py-1 px-2"
CHECKBOX_CLASSES = "form-checkbox h-5 w-5 text-blue-500"

# -------------------------------
# 🔹 ForceMember Form
# -------------------------------
class ForceModelForm(forms.ModelForm):
    svc_join = forms.CharField(
        label='Svc Join',
        required=False,
        widget=forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'DD/MM/YYYY'}),
        initial=date(current_year, 1, 1).strftime("%d/%m/%Y")
    )
    rab_join = forms.CharField(
        label='RAB Join',
        required=False,
        widget=forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'DD/MM/YYYY'}),
        initial=date(current_year, 1, 1).strftime("%d/%m/%Y")
    )
    birth_day = forms.CharField(
        label='Birth Day',
        required=False,
        widget=forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'DD/MM/YYYY'}),
        initial=date(current_year, 1, 1).strftime("%d/%m/%Y")
    )

    class Meta:
        model = ForceMember
        exclude = ['company']
        fields = [
            'no', 'name', 'rank', 'force', 
            'svc_join','mother_unit', 'rab_join', 'birth_day',
            'nid', 'email', 'phone', 'wf_phone','company',
        ]
        labels = {
            'no': 'Personal No',
            'name': 'Full Name',
            'rank': 'Rank',
            'force': 'Force',
            'mother_unit': 'moteher_unit',
            'svc_join': 'Svc Join',
            'rab_join': 'RAB Join',
            'birth_day': 'Birth Day',
            'nid': 'NID',
            'email': 'Email',
            'phone': 'Phone',
            'wf_phone': 'Wife Phone',
            'company':'company',
        }
        widgets = {
            'no': forms.NumberInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Personal Number'}),
            'name': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Full Name'}),
            'rank': forms.Select(attrs={'class': SELECT_CLASSES}),
            'force': forms.Select(attrs={'class': SELECT_CLASSES}),
            'mother_unit': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Unit Name....'}),
            'company': forms.Select(attrs={'class': SELECT_CLASSES}),
            'nid': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'NID'}),
            'email': forms.EmailInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Email'}),
            'phone': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Phone Number'}),
            'wf_phone': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Wife Phone Number'}),
        }

    # -------------------------------
    # Custom clean methods for DD/MM/YYYY
    # -------------------------------
    def clean_svc_join(self):
        data = self.cleaned_data['svc_join']
        if data:
            try:
                return datetime.strptime(data, "%d/%m/%Y").date()
            except ValueError:
                raise forms.ValidationError("Invalid date format. Use DD/MM/YYYY.")
        return None

    def clean_rab_join(self):
        data = self.cleaned_data['rab_join']
        if data:
            try:
                return datetime.strptime(data, "%d/%m/%Y").date()
            except ValueError:
                raise forms.ValidationError("Invalid date format. Use DD/MM/YYYY.")
        return None

    def clean_birth_day(self):
        data = self.cleaned_data['birth_day']
        if data:
            try:
                return datetime.strptime(data, "%d/%m/%Y").date()
            except ValueError:
                raise forms.ValidationError("Invalid date format. Use DD/MM/YYYY.")
        return None

# -------------------------------
# 🔹 Present Address Form
# -------------------------------
class PresentModelForm(forms.ModelForm):
    class Meta:
        model = PresentAddress
        fields = ['house', 'road', 'sector', 'village','post', 'thana', 'district', 'division']
        labels = {
            'house': 'House No',
            'road': 'Road No',
            'sector': 'Sector',
            'village': 'Village',
            'post':'post',
            'thana': 'Police Station',
            'district': 'District',
            'division': 'Division',
        }
        widgets = {f: forms.TextInput(attrs={'class': INPUT_CLASSES}) for f in fields}

# -------------------------------
# 🔹 Permanent Address Form
# -------------------------------
class PermanentModelForm(forms.ModelForm):
    same_as_present = forms.BooleanField(
        required=False,
        label='Same as Present Address',
        widget=forms.CheckboxInput(attrs={'class': CHECKBOX_CLASSES})
    )

    class Meta:
        model = PermanentAddress
        fields = ['house', 'road', 'sector', 'village','post', 'thana', 'district', 'division']
        labels = {
            'house': 'House No',
            'road': 'Road No',
            'sector': 'Sector',
            'village': 'Village',
            'post':'post',
            'thana': 'Police Station',
            'district': 'District',
            'division': 'Division',
        }
        widgets = {f: forms.TextInput(attrs={'class': INPUT_CLASSES}) for f in fields}



# -------------------------------
# 🔹 Company Assign Form
# -------------------------------
class CompanySelectForm(forms.ModelForm):
    class Meta:
        model = ForceMember
        fields = ['company']

tasks/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib import messages
from tasks.models import ForceMember
from tasks.forms import ForceModelForm,CompanySelectForm, PresentModelForm, PermanentModelForm
from django.db.models import Count, Prefetch, Q


# ---------------------------------------------------
# Dashboard
# ---------------------------------------------------
def Dashboard(request):
   
    return render(request, 'dashboard/dashboard.html')

# ---------------------------------------------------
# Bn HQ
# ---------------------------------------------------
def Br(request):
    return render(request, 'bnhq/list.html')
# ---------------------------------------------------
# Force Bio Data Entry 
# ---------------------------------------------------
def Force_bio(request):
    if request.method == 'POST':
        force_form = ForceModelForm(request.POST)
        present_form = PresentModelForm(request.POST)
        permanent_form = PermanentModelForm(request.POST)

        # Form validation
        if force_form.is_valid() and present_form.is_valid() and permanent_form.is_valid():
            # Save ForceMember
            force = force_form.save()
            # force.company.add(Company.objects.get(id=1))

            # Save PresentAddress
            present = present_form.save(commit=False)
            present.member = force
            present.save()

            # Save PermanentAddress
            permanent = permanent_form.save(commit=False)
            permanent.member = force
            permanent.save()

            # Success message
            messages.success(request, "saved successfully!")
            return redirect('force-bio')

        else:
            # Debug: print form errors to console
            messages.error(request, "Please fix the errors!")
            print("errors:", force_form.errors)
            print("errors:", present_form.errors)
            print("errors:", permanent_form.errors)

    else:
        force_form = ForceModelForm()
        present_form = PresentModelForm()
        permanent_form = PermanentModelForm()

    context = {
        'force_form': force_form,
        'present_form': present_form,
        'permanent_form': permanent_form,
    }
    return render(request, 'dashboard/bio.html', context)

# ---------------------------------------------------
# 
# ---------------------------------------------------
# views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

def Force_detail(request):
    members = ForceMember.objects.all().select_related(
        'present_address', 'permanent_address'
    )

    # Handle AJAX POST
    if request.method == "POST":
        member_id = request.POST.get("member_id")
        member = get_object_or_404(ForceMember, id=member_id)

        form = CompanySelectForm(request.POST, instance=member)

        if form.is_valid():
            form.save()

            # AJAX request → return JSON
            if request.headers.get("X-Requested-With") == "XMLHttpRequest":
                return JsonResponse({
                    "success": True,
                    "company_name": member.company  # updated value
                })

            return redirect("force-detail")

        else:
            if request.headers.get("X-Requested-With") == "XMLHttpRequest":
                return JsonResponse({"success": False})

    # For GET request → load table
    forms_dict = {m.id: CompanySelectForm(instance=m) for m in members}

    return render(request, "bnhq/force_detail.html", {
        "members": members,
        "forms_dict": forms_dict,
    })


#.......................
# Address................
# ....................... 

def Address(request, member_id):
    m = get_object_or_404(ForceMember, id=member_id)

    context = {
        "m": m,
        "present_dict": {
            "House": m.present_address.house,
            "Road": m.present_address.road,
            "Sector": m.present_address.sector,
            "Village": m.present_address.village,
            "Post": m.present_address.post,
            "District": m.present_address.district,
        },
        "permanent_dict": {
            "House": m.permanent_address.house,
            "Road": m.permanent_address.road,
            "Sector": m.permanent_address.sector,
            "Village": m.permanent_address.village,
            "Post": m.permanent_address.post,
            "District": m.permanent_address.district,
        },
        "service_dict": {
            "Svc Join": m.svc_join,
            "RAB Join": m.rab_join, 
            "Mother_unit":m.mother_unit,
            "NID": m.nid,
            "Birth Day": m.birth_day,
            "WF Phone": m.wf_phone,
        },
    }
    return render(request, "bnhq/address.html", context)

tasks/templates/bnhq/address.html
{% extends "dashboard/css.html" %} 
{% load widget_tweaks %}
{% block title %}Force Detail{% endblock title %}

{% block content %} 

        <h1 class="text-4xl font-bold text-gray-800 mb-2 text-center">
            {{ m.rank }} - {{ m.name }} - {{ m.force }}
        </h1>

<main class="flex justify-center p-6 gap-4">

        <!-- Present Address Card -->
        <div class="bg-white shadow-sm rounded-md border border-gray-300 p-6 gap-4">
            <h2 class="text-3xl font-semibold text-gray-700 mb-2 flex items-center gap-2 justify-center">🏠 Present Address</h2>
            <div class="space-y-1 text-sm text-gray-700">
                {% for label, value in present_dict.items %}
                <div class="flex justify-between border-b border-gray-300 px-4 py-2">
                    <span class="font-medium text-2xl text-gray-600">{{ label }}:</span>
                    <span class="text-2xl">{{ value|default:"—" }}</span>
                </div>
                {% endfor %}
            </div>
        </div>

        <!-- Permanent Address Card -->
        <div class="bg-white shadow-sm rounded-md border border-gray-300 p-3">
            <h2 class="text-3xl font-semibold text-gray-700 mb-2 flex items-center gap-2 justify-center">🏡 Permanent Address</h2>
            <div class="space-y-1 text-sm text-gray-700">
                {% for label, value in permanent_dict.items %}
                <div class="flex justify-between border-b border-gray-200 px-4 py-2">
                    <span class="font-medium text-2xl text-gray-600">{{ label }}:</span>
                    <span class="text-2xl">{{ value|default:"—" }}</span>
                </div>
                {% endfor %}
            </div>
        </div>

        <!-- Service Information Card -->
        <div class="bg-white shadow-sm rounded-md border border-gray-300 p-3">
            <h2 class="text-3xl font-semibold text-gray-700 mb-2 flex items-center gap-2 justify-center">🛡️ Service Information</h2>
            <div class="space-y-1 text-sm text-gray-700">
                {% for label, value in service_dict.items %}
                <div class="flex justify-between border-b border-gray-200 px-4 py-2">
                    <span class="font-medium text-2xl text-gray-600">{{ label }}:</span>
                    <span class="text-2xl">{{ value|default:"—" }}</span>
                </div>
                {% endfor %}
            </div>
        </div>


        </main>
        <!-- Back Button -->
        <div class="bg-blue-700 text-center text-gray-200 text-3xl mt-2">
            <a href="{% url 'force-detail' %}" class="inline-block bg-blue-500 text-white px-4 py-1 rounded hover:bg-blue-600 transition">
                Back 
            </a>
        </div>

    

{% endblock content %}

tasks/templates/bnhq/all_force.html
{% extends "dashboard/css.html" %}
{% load widget_tweaks %}

{% block title %}Posting{% endblock %}

{% block content %}

<table class="w-full border-collapse shadow rounded-lg overflow-hidden">
    <!-- Header -->
    <thead class="bg-blue-500 text-3xl font-semibold text-white">
        <tr>
            <th class="p-2 border">Ser</th>
            <th class="p-2 border">No</th>
            <th class="p-2 border">Rank</th>
            <th class="p-2 border">Name</th>
            <th class="p-2 border">Force</th>
            <th class="p-2 border">Company</th>
            <th class="p-2 border">Phone</th>
            <th class="p-2 border">Email</th>
            <th class="p-2 border">Detail</th>
            <th class="p-2 border">Action</th>
        </tr>
    </thead>

    <tbody>
    {% for force in all_force %}
        <tr class="bg-white text-lg hover:bg-blue-50">
            <td class="p-2 border">{{ forloop.counter }}</td>
            <td class="p-2 border">{{ force.no }}</td>
            <td class="p-2 border">{{ force.rank}}</td>
            <td class="p-2 border font-semibold">{{ force.name }}</td>
            <td class="p-2 border">{{ force.force}}</td>
             <td class="p-2 border">{{ force.get_company_display }}</td>
            <td class="p-2 border">{{ force.phone }}</td>
            <td class="p-2 border">{{ force.email }}</td>

            <!-- View Button -->
            <td class="p-2 border text-center">
                <a href="{% url 'force_detail' force.id %}" 
                   class="bg-blue-500 text-white px-3 py-1 rounded-md hover:bg-blue-600">
                    View
                </a>
            </td>

            <!-- Action Button -->
            <td class="p-2 border text-center">
                Send
               
            </td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="10" class="text-center p-4 text-gray-500">No records found.</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

tasks/templates/bnhq/force_detail.html
{% extends "dashboard/css.html" %}
{% load widget_tweaks %}
{% load dict_extras %}
{% block title %}All Forces{% endblock %}

{% block content %}

<main class="p-6 space-y-6">

<table class="bg-white table-auto w-full border">
<thead>
<tr class="bg-amber-400 text-3xl">
    <th>Ser</th>
    <th>Per No</th>
    <th>Rank</th>
    <th>Name</th>
    <th>Force</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Company</th>
    <th>Detail</th>
    <th>Send</th>
</tr>
</thead>

<tbody>
{% for m in members %}
<tr class="text-center border text-2xl hover:bg-cyan-200 cursor-pointer">

    <td>{{ forloop.counter }}</td>
    <td>{{ m.no }}</td>
    <td>{{ m.rank }}</td>
    <td>{{ m.name }}</td>
    <td>{{ m.force }}</td>
    <td>{{ m.phone }}</td>
    <td>{{ m.email }}</td>

    <!-- Company column -->
    <td class="company-name">
        {{ m.company }}
    </td>

    <!-- View -->
    <td>
        <a href="{% url 'address' m.id %}" 
           class="bg-green-500 px-3 py-1 rounded hover:bg-amber-300">
           View
        </a>
    </td>

    <!-- AJAX Assign Form -->
    <td>
        <form class="assign-form">

            {% csrf_token %}
            {% with form=forms_dict|get_item:m.id %}
                {{ form.company }}
            {% endwith %}

            <input type="hidden" name="member_id" value="{{ m.id }}">

            <button type="button"
                class="assign-btn bg-purple-500 text-white px-3 py-1 rounded hover:bg-purple-700">
                Assign
            </button>

        </form>
    </td>

</tr>
{% endfor %}
</tbody>
</table>

</main>

<script>
document.querySelectorAll(".assign-btn").forEach(button => {
    button.addEventListener("click", function () {

        let form = this.closest(".assign-form");
        let row = this.closest("tr");
        let formData = new FormData(form);

        fetch("", {
            method: "POST",
            headers: { "X-Requested-With": "XMLHttpRequest" },
            body: formData
        })
        .then(response => response.json())
        .then(data => {

            if (data.success) {

                // Update company instantly
                row.querySelector(".company-name").innerText = data.company_name;

                // Highlight row
                row.style.backgroundColor = "#d1fad1"; // light green
            }
        });
    });
});
</script>

{% endblock %}

tasks/templates/bnhq/list.html
{% extends "dashboard/css.html" %} 
{% load widget_tweaks %}

{% block title %}All Branches{% endblock title %}

{% block content %}
<main class="max-w-[800px] mx-auto p-6 bg-white rounded-sm">
    {% comment %} <h1 class="font-extrabold mb-8 text-gray-900 text-center">Go to All Branches</h1> {% endcomment %}

    <div class="flex flex-col gap-6 justify-center">
        <!-- Card 1 -->
        <div class=" grid grid-cols-1 bg-gradient-to-r from-pink-400 to-pink-600 font-semibold text-4xl py-6 rounded-xl shadow-xl transform hover:scale-105 hover:shadow-2xl transition-all duration-300 cursor-pointer text-left px-6">
           <a href="{% url 'br' %}">
             Bn HQ 
            <span>Total Manpower = </span> 
           </a>
            
        </div>

        <!-- Card 2 --> 
       <a href="{% url 'force-detail' %}">
            <div class="bg-gradient-to-r from-purple-400 to-purple-600 font-semibold text-4xl py-6 rounded-xl shadow-xl transform hover:scale-105 hover:shadow-2xl transition-all duration-300 cursor-pointer text-left px-6">
            All Force Details
        </div>
        </a>
        

        <!-- Card 3 -->
        <div class="bg-gradient-to-r from-blue-400 to-blue-600 font-semibold text-4xl py-6 rounded-xl shadow-xl transform hover:scale-105 hover:shadow-2xl transition-all duration-300 cursor-pointer text-left px-6">
         Duty
        </div>

        {% comment %} <!-- Card 4 -->
        <div class="bg-gradient-to-r from-green-400 to-green-600 font-semibold text-4xl py-6 rounded-xl shadow-xl transform hover:scale-105 hover:shadow-2xl transition-all duration-300 cursor-pointer text-left px-6">
            A Br
        </div>

        <!-- Card 5 -->
        <div class="bg-gradient-to-r from-yellow-400 to-yellow-600 font-semibold text-4xl py-6 rounded-xl shadow-xl transform hover:scale-105 hover:shadow-2xl transition-all duration-300 cursor-pointer text-left px-6">
            Mi Branch
        </div>

        <!-- Card 6 -->
        <div class="bg-gradient-to-r from-orange-400 to-orange-600 font-semibold text-4xl py-6 rounded-xl shadow-xl transform hover:scale-105 hover:shadow-2xl transition-all duration-300 cursor-pointer text-left px-6">
            Mt
        </div>

        <!-- Card 7 -->
        <div class="bg-gradient-to-r from-red-400 to-red-600 font-semibold text-4xl py-6 rounded-xl shadow-xl transform hover:scale-105 hover:shadow-2xl transition-all duration-300 cursor-pointer text-left px-6">
            Other Branch
        </div> {% endcomment %}
    </div>
</main>
{% endblock content %}

tasks/templates/bnhq/posting.html
✅ PART–2: কোম্পানি অনুযায়ী আলাদা লিস্ট

Company A → সকল সদস্য


Company B → সকল সদস্য
এগুলো আলাদা পেইজে বা একই ড্যাশবোর্ডে।



✅ 3. একই টেবিলে কোম্পানি চেঞ্জ করা হলে রঙ বা স্ট্যাটাস দেখানো
যেমন:
"Sent Successfully" ব্যাজ।

✅ 4. একসাথে একাধিক সদস্য সিলেক্ট → একসাথে Send করা
bulk update system.

✅ 5. Company history (posting history) সেভ করা
এক সদস্য কতবার কোন কোম্পানিতে গেছে—History table তৈরি।

⚡ আপনি ঠিক কোনটা করতে চান?
"তার পরে" মানে কোন ফিচারটি চান—শুধু নম্বর লিখে বললেই হবে।